export const froalaConfig = {
  key: process.env.REACT_APP_FORALA_KEY,
  inlineMode: false,
  linkAlwaysBlank: true,
  heightMin: 350,
  pluginsEnabled: [
    'align',
    'charCounter',
    'codeBeautifier',
    'codeView',
    'colors',
    'draggable',
    'embedly',
    'emoticons',
    'entities',
    'file',
    'fontAwesome',
    'fontFamily',
    'fontSize',
    'fullscreen',
    'image',
    'imageTUI',
    'imageManager',
    'inlineStyle',
    'inlineClass',
    'lineBreaker',
    'lineHeight',
    'link',
    'lists',
    'paragraphFormat',
    'paragraphStyle',
    'quote',
    'save',
    'table',
    'url',
    'video',
    'wordPaste',
    'spellChecker',
  ],
  imageUploadParam: 'media',
  imageUploadURL: process.env.REACT_APP_API_URL + '/medias',
  fileUploadParam: 'media',
  fileUploadURL: process.env.REACT_APP_API_URL + '/medias',
  videoUploadParam: 'media',
  videoUploadURL: process.env.REACT_APP_API_URL + '/medias',
  imageManagerLoadURL: process.env.REACT_APP_API_URL + '/medias/froala',
  wordCounter: true,
  wordCounterLabel: 'words',
};
